##################################################
# Generated by the MiriATE Script Generator
# Version: 3.4.3
# DO NOT EDIT MANUALLY!
# Only edit with the MiriATE Script Generator.
##################################################
# Last edited on: 07 Jun 2013 11:21:23 BST
##################################################

#comment
set autoVariable0 [miriate::av::regioncompare 90.0 "ChannelInfoBar_Igloo" "ChannelInfoBar_Igloo_Mask" "SYNC" "ALL" 5000 "ANY"]
